services:
  - type: web
<<<<<<< HEAD
    name: medtech-ai
=======
    name: medtech-backend
>>>>>>> 01af1829cdd630b53666104436f47e3e9da14f41
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      cd ../frontend
      npm install
      npm run build
<<<<<<< HEAD
      mkdir -p ../backend/frontend/dist
      cp -r dist/* ../backend/frontend/dist/
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      PYTHON_VERSION: 3.12.2
=======
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    staticPublishPath: frontend/dist
>>>>>>> 01af1829cdd630b53666104436f47e3e9da14f41
